# Numpy的属性

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(array.ndim)  #二维矩阵

#array = np.array([[[1,2,3],
#                  [4,5,6],
#                  [7,8,9]]])
#print(array)
#print(array.ndim)  #三维矩阵

2


In [4]:
print(array.shape)#矩阵的形状

(3, 3)


In [5]:
print(array.size)#矩阵的大小，矩阵中有9个元素，大小为9

9


In [6]:
print(array.dtype)#矩阵中元素的属性

int32
