# 创建不同维度的array 数组

In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3],dtype = int)#一维数组，数据类型为int32
print(a.dtype)

int32


In [8]:
b = np.array([1,2,3],dtype = float)
print(b.dtype)

float64


In [10]:
c = np.array([1,2,3])
print(c)

[1 2 3]


In [11]:
d = np.array([[1,2,3],
              [4,5,6]])
print(d)

[[1 2 3]
 [4 5 6]]


# 生成全为0的数组

In [12]:
zero = np.zeros((2,3))#2行3列
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


# 生成全为1的数组

In [13]:
one = np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
two = np.twos((5,5))
print(two)

AttributeError: module 'numpy' has no attribute 'twos'

In [35]:
empty = np.empty((2,3))#生成的数组中的值接近于0但不等于0
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
5 / empty[0][0]  #正负无穷inf

<ipython-input-19-fa2b823379d6>:1: RuntimeWarning: divide by zero encountered in double_scalars
  5 / empty[0][0]


inf

In [20]:
5 / zero[0][0]

<ipython-input-20-3e2157282303>:1: RuntimeWarning: divide by zero encountered in double_scalars
  5 / zero[0][0]


inf

# 生成0到9的一维数组  arange()函数

In [24]:
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
f = np.arange(4,12)
print(f)

[ 4  5  6  7  8  9 10 11]


In [32]:
g = np.arange(1,20,3)  #步长为3
print(g)

[ 1  4  7 10 13 16 19]


# reshape()函数 重新定义数组的形状

In [34]:
h = np.arange(8).reshape(4,2)  #np.arange(8) 生成0到7的一维数组 reshape(2,4)变换为2行4列的2维数组
print(h)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
