In [1]:
import numpy as np

# 一维和二维数组的建立

In [22]:
arr_1 = np.array([[1,2,3],  #二维的 [ [ ],[ ] ]
                  [4,5,6]])
arr_2 = np.array([[1,1,2],
                  [2,3,3]])
print(arr_1)
print(arr_2)
arr_0 = np.array([1,2,3])  #一维的 [ ]
print(arr_0)

[[1 2 3]
 [4 5 6]]
[[1 1 2]
 [2 3 3]]
[1 2 3 4]


In [8]:
print(arr_1+arr_2)  #数组的加法是按位加法

[[2 3 5]
 [6 8 9]]


In [10]:
print(arr_1-arr_2)  #数组的减法是按位的减法

[[0 1 1]
 [2 2 3]]


In [41]:
print(arr_1 * arr_2)  #按位乘法 点乘

[[ 1  2  6]
 [ 8 15 18]]


In [14]:
print(arr_1)
print(arr_2)

print("\n")

print(arr_1 ** arr_2)

[[1 2 3]
 [4 5 6]]
[[1 1 2]
 [2 3 3]]


[[  1   2   9]
 [ 16 125 216]]


In [15]:
print(arr_1 / arr_2)

[[1.         2.         1.5       ]
 [2.         1.66666667 2.        ]]


In [19]:
print(arr_1 // arr_2)  #取整

[[1 2 1]
 [2 1 2]]


In [20]:
print(arr_1 % arr_2)  #取余

[[0 0 1]
 [0 2 0]]


In [24]:
arr_0 = np.array([1,2,3])  #一维的 [ ]
print(arr_0)
print(arr_1 / arr_0)

[1 2 3]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [29]:
arr_10 = np.array([1,2,3,4])  #一维的 [ ]
print(arr_10)
try:
    x = arr_1 / arr_10
except ValueError:
    print("It's wrong.")
else:
    print(x)

[1 2 3 4]
It's wrong.


In [33]:
print(arr_1)

print("\n")

print(arr_1 + 2)  #所有元素加2

print("\n")

print(arr_1 - 2)  #所有元素减2

print("\n")

print(arr_1 * 2)  #所有元素乘2

print("\n")

print(arr_1 / 2)  #所有元素除2

[[1 2 3]
 [4 5 6]]


[[3 4 5]
 [6 7 8]]


[[-1  0  1]
 [ 2  3  4]]


[[ 2  4  6]
 [ 8 10 12]]


[[0.5 1.  1.5]
 [2.  2.5 3. ]]


# 把返回的结果保存在新数组中

In [35]:
arr_3 = arr_1 > 3  #判断元素是否大于三
print(arr_3)

[[False False False]
 [ True  True  True]]


# 创建指定元素的数组 函数ones(shape, dtype = None, order = 'C')

In [39]:
arr_4 = np.ones((3,5))  #ones( (a,b) )
print(arr_4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 矩阵乘法 函数dot()

In [44]:
print(arr_1)
print("\n")
print(arr_4)
print("\n")

c = np.dot(arr_1,arr_4)  #矩阵乘法 arr_1 2*3 arr_2 3*5 c 2*5
print(c)

[[1 2 3]
 [4 5 6]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[ 6.  6.  6.  6.  6.]
 [15. 15. 15. 15. 15.]]


In [49]:
#前一种方式 调用np的dot函数
#矩阵乘法的另一种方式  调用arr_1的dot()方法
d = arr_1.dot(arr_4)
print(d)

[[ 6.  6.  6.  6.  6.]
 [15. 15. 15. 15. 15.]]


# 转置矩阵  .T  .transpose()

In [59]:
print(arr_1)
print(arr_1.T)  #arr_1的转置矩阵
print(arr_1.transpose())  #arr_1的转置矩阵 arr_1的transpose()方法
print(np.transpose(arr_1))  #arr_1的转置矩阵 np的transpose()函数

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
