In [1]:
import numpy as np

# numpy生成0到1的随机数数组 .random.random( (a,b) )

In [3]:
sample_1 = np.random.random((3,2))  #0到1的随机数
print(sample_1)

[[0.12796212 0.70735022]
 [0.92873313 0.44114069]
 [0.52829167 0.01924996]]


# 生成符合正态分布的随机数 .random.normal( size=(a,b) )

In [10]:
sample_2 = np.random.normal()  #生成符合标准正态分布的随机数
print(sample_2)

2.2623095542271807


In [11]:
sample_2 = np.random.normal(size=(3,2))  #生成符合标准正态分布的随机数
print(sample_2)

[[-0.59366033 -0.52711003]
 [ 0.33191856  1.18146973]
 [ 0.9903453   1.8570276 ]]


# 生成随机整数 .random.randint(x,y,size=(a,b))

In [1]:
sample_3 = np.random.randint(0,10,size=(3,2))  #生成0到10的随机整数
print(sample_3)

[[9 8]
 [0 7]
 [4 6]]


# 求和 将数组中所有元素相加

In [11]:
np.sum(sample_1)

2.752727791595753

In [14]:
#对列求和 axis=0
np.sum(sample_1,axis=0)

array([1.58498692, 1.16774087])

In [16]:
#对行求和 axis=1
np.sum(sample_1,axis=1)

array([0.83531234, 1.36987382, 0.54754163])

# 求元素的最小值和最大值

In [9]:
print(np.min(sample_1))

print("\n")

print(np.max(sample_1))

0.019249960382873965


0.9287331319712548


# 找数组中最小元素的索引 argmin()

In [21]:
print(sample_1)

print("\n")

print(np.argmin(sample_1))

[[0.12796212 0.70735022]
 [0.92873313 0.44114069]
 [0.52829167 0.01924996]]


5


# 找数组中最大元素的索引 argmax()

In [22]:
print(sample_1)

print("\n")

print(np.argmax(sample_1))

[[0.12796212 0.70735022]
 [0.92873313 0.44114069]
 [0.52829167 0.01924996]]


2


# 求平均值

In [28]:
print(np.mean(sample_1))  #使用np中的函数mean()

0.45878796526595883


In [27]:
print(sample_1.mean())  #使用mean()方法

0.45878796526595883


# 求中位数 双数时：取中间两个数的平均值 单数时：取中间数

In [29]:
np.median(sample_1)

0.4847161793479178

In [31]:
test_arr = np.array([1,2,3,4,5])
np.median(test_arr)

3.0

# 求数组中每个元素开方的结果

In [32]:
np.sqrt(test_arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

[5 4 5 2 0 8 4 5 1 1]
[[9 7 7 2 0 2 8 7 9 4]]


# 生成随机数，使用numpy中的sort()函数对随机数进行排序

In [43]:
sample_4 = np.random.randint(0,10,size=10)  #size = 10  [......]
print(sample_4)

sample_4 = np.random.randint(0,10,size=(1,10))  #size = (1,10)  [ [......] ]
print(sample_4)

np.sort(sample_4)

[2 6 4 9 4 5 9 5 6 9]
[[7 7 5 8 5 9 9 8 4 7]]


array([[4, 5, 5, 7, 7, 7, 8, 8, 9, 9]])

In [46]:
print(sample_1)
np.sort(sample_1)  #默认axis = 1 对sample_1的每一行进行排序

[[0.12796212 0.70735022]
 [0.92873313 0.44114069]
 [0.52829167 0.01924996]]


array([[0.12796212, 0.70735022],
       [0.44114069, 0.92873313],
       [0.01924996, 0.52829167]])

In [63]:
sample_test = np.random.random((3, 2))
print(sample_test)

print("\n")

print(np.sort(sample_test, axis=0))  #axis = 0 按列排序 axis = 1 按行排序

print("\n")
print(sample_test)

[[0.75488722 0.42117512]
 [0.01494067 0.97745051]
 [0.05173242 0.84022814]]


[[0.01494067 0.42117512]
 [0.05173242 0.84022814]
 [0.75488722 0.97745051]]


[[0.75488722 0.42117512]
 [0.01494067 0.97745051]
 [0.05173242 0.84022814]]


# numpy的clip()函数

In [3]:
sample_4 = np.random.randint(0,10,size=(1,10))  #size = (1,10)  [ [......] ]
print(sample_4)

np.clip(sample_4,2,7)#大于7的数变为7，小于2的数变为2

[[9 2 5 9 9 5 0 6 3 9]]


array([[7, 2, 5, 7, 7, 5, 2, 6, 3, 7]])