In [2]:
import numpy as np

In [3]:
arr_1 = np.arange(2, 14)  #创建一个2到13的数组
print(arr_1)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [4]:
print(arr_1[2])

4


In [5]:
print(arr_1[1:4])  #切片   减1原则

[3 4 5]


In [6]:
print(arr_1[1:-1])

[ 3  4  5  6  7  8  9 10 11 12]


In [7]:
print(arr_1[:-1])

[ 2  3  4  5  6  7  8  9 10 11 12]


In [4]:
print(arr_1[1:])

[ 3  4  5  6  7  8  9 10 11 12 13]


In [5]:
print(arr_1[-3:])

[11 12 13]


In [10]:
arr_2 = arr_1.reshape(3,4)#reshape()函数有返回值
print(arr_2)
print(arr_1)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [11]:
print(arr_2[0])

[2 3 4 5]


In [13]:
print(arr_2[0][0])#确定位置的数据

2


In [15]:
print(arr_2[0,0])

2


In [17]:
print(arr_2[:,2])  #所有行的第2列

[ 4  8 12]


In [18]:
for i in arr_2:  #迭代的是arr_2数组中的行
    print(i)

[2 3 4 5]
[6 7 8 9]
[10 11 12 13]


In [19]:
for i in arr_2.T:
    print(i)

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


# 使用.flat进行扁平化，迭代的是数组中的元素

In [22]:
for i in arr_2.flat:  #扁平化 迭代的是arr_2的元素
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
