In [2]:
import numpy as np

np.where()用法

In [3]:
song_array = np.array([10,20,30,40,50])
np.where(song_array > 30)

(array([3, 4], dtype=int64),)

In [6]:
song_array[np.where(song_array > 30)]

array([40, 50])

不常用的格式

In [10]:
arr = np.array([1,10,3.5,'str'],dtype = object)
arr

array([1, 10, 3.5, 'str'], dtype=object)

In [11]:
arr *2

array([2, 20, 7.0, 'strstr'], dtype=object)

np.asarray()重做数组

In [18]:
arr = np.array([1,2,3,4,5])
arr2 = np.asarray(arr,dtype = np.float32)

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
arr2

array([1., 2., 3., 4., 5.], dtype=float32)

.astype()重做数组

In [21]:
arr.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

### 数组的数值计算

In [23]:
import numpy as np

指定要进行的操作是沿着什么轴

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.sum(arr)

21

In [27]:
np.sum(arr,axis=0)

array([5, 7, 9])

In [28]:
arr.ndim#维度

2

In [29]:
np.sum(arr,axis=1)

array([ 6, 15])

In [31]:
np.sum(arr,axis=-1)#最后一个轴

array([ 6, 15])

In [33]:
arr.sum(axis=0)

array([5, 7, 9])

求一个乘积

In [36]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr.prod()#1*2*3*4*5*6

720

In [38]:
arr.prod(axis=0)

array([ 4, 10, 18])

In [39]:
arr.prod(axis=1)

array([  6, 120])

求最大最小值 求最大最小值的索引

In [40]:
arr.min()

1

In [41]:
arr.max()

6

In [42]:
arr.max(axis=0)

array([4, 5, 6])

In [43]:
arr.max(axis=1)

array([3, 6])

In [44]:
arr.argmax()

5

In [45]:
arr.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [47]:
arr.argmin(axis=1)

array([0, 0], dtype=int64)

求均值

In [48]:
arr.mean()

3.5

In [49]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

标准差

In [50]:
arr.std()

1.707825127659933

In [51]:
arr.std(axis=0)

array([1.5, 1.5, 1.5])

方差

In [52]:
arr.var()

2.9166666666666665

做限制

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

In [55]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

做近似 四舍五入

In [57]:
arr = np.array([1.2,3.56,6.41])
arr.round()

array([1., 4., 6.])

In [60]:
#指定四舍五入的精度
arr.round(decimals=1)#decimals 小数

array([1.2, 3.6, 6.4])

排序

In [62]:
import numpy as np

In [63]:
arr = np.array([[1.5,1.3,7.5],
                [5.6,7.8,1.2]])
arr

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [64]:
np.sort(arr)#默认用最后一个轴进行排序 axis=-1

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [65]:
np.sort(arr,axis=0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [66]:
arr

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [68]:
np.argsort(arr)#返回的是原来的索引值

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

查找应插入元素以保持顺序的索引

In [70]:
arr = np.linspace(0,10,10)
arr

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [74]:
values = np.array([2.5,6.5,9.5])
values

array([2.5, 6.5, 9.5])

In [77]:
np.searchsorted(arr,values)#要求arr是排序好的数组

array([3, 6, 9], dtype=int64)

同时操作多个列

In [1]:
arr = np.array([[1,0,6],[1,7,0],[2,3,1],[2,4,0]])
arr

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [3]:
index = np.lexsort([-1*arr[:,0],arr[:,2]])#第0列倒叙 第2列升序
index

array([3, 1, 2, 0], dtype=int64)

In [6]:
arr = arr[index]#在第2列升序的前提下 对第0列进行降序 如第2列前两个数都为0 第1列的前两个数进行了一个降序
arr

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])

### 数组形状

In [8]:
import numpy as np

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr.shape

(10,)

改变数组形状的两种方法

In [13]:
arr.shape = 2,5
arr.shape

(2, 5)

In [15]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
arr.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
#数组大小不能改变
arr.shape = 3,4 #3*4=12 > 10

ValueError: cannot reshape array of size 10 into shape (3,4)

In [22]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr.shape

(10,)

In [24]:
arr = arr[np.newaxis,:]
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
arr.shape

(1, 10)

In [29]:
arr = np.arange(10)
arr = arr[:,np.newaxis]
arr.shape

(10, 1)

In [30]:
arr = np.arange(10)
arr = arr[:,np.newaxis,np.newaxis]
arr.shape

(10, 1, 1)

In [31]:
arr = arr[:,np.newaxis]
arr.shape

(10, 1, 1, 1)

In [32]:
#压缩 去掉多余的空轴
arr = arr.squeeze()
arr.shape

(10,)

In [34]:
arr.shape = 2,5
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

转置

In [36]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [37]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [38]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
#把转置后的值重新赋值
arr = arr.T
arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### 数组的连接

In [41]:
a = np.array([[123,456,678],[3214,444,555]])
a

array([[ 123,  456,  678],
       [3214,  444,  555]])

In [47]:
b = np.array([[23,476,678],[14,44,55]])
b

array([[ 23, 476, 678],
       [ 14,  44,  55]])

In [52]:
c = np.concatenate((a,b))#a,b要写成类似于元祖的格式
c

array([[ 123,  456,  678],
       [3214,  444,  555],
       [  23,  476,  678],
       [  14,   44,   55]])

In [53]:
c = np.concatenate((a,b),axis=1)
c

array([[ 123,  456,  678,   23,  476,  678],
       [3214,  444,  555,   14,   44,   55]])

In [54]:
c.shape

(2, 6)

竖着拼接还是横着拼接

In [55]:
np.vstack((a,b))

array([[ 123,  456,  678],
       [3214,  444,  555],
       [  23,  476,  678],
       [  14,   44,   55]])

In [56]:
np.hstack((a,b))

array([[ 123,  456,  678,   23,  476,  678],
       [3214,  444,  555,   14,   44,   55]])

In [58]:
a

array([[ 123,  456,  678],
       [3214,  444,  555]])

拉平

In [59]:
a.flatten()

array([ 123,  456,  678, 3214,  444,  555])

In [65]:
a


array([[ 123,  456,  678],
       [3214,  444,  555]])

In [66]:
#a.shape

(2, 3)

In [64]:
a.ravel()

array([ 123,  456,  678, 3214,  444,  555])

In [67]:
#a.ravel().shape

(6,)

In [68]:
# P8课